# Generated by Django 5.2.5 on 2026-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20)),
                ('held_by', models.CharField(blank=True, max_length=100, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['row_id', 'number'], name='seats_seat_row_id_c85bbd_idx')],
                'unique_together': {('row_id', 'number')},
            },
        ),
    ]
