# Generated by Django 5.2.5 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'Standard'), ('ECONOMY', 'Economy')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
