# Generated by Django 5.2.5 on 2026-01-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
