# Generated by Django 5.2.5 on 2026-01-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0007_movie_genre_movie_poster_url_moviereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
