# Generated by Django 5.2.5 on 2026-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0008_delete_moviereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='is_dynamic_pricing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
