# Generated by Django 5.2.5 on 2026-01-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0009_showtime_is_dynamic_pricing_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='is_dynamic_pricing_enabled',
        ),
    ]
