# Generated by Django 5.2.5 on 2026-01-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0011_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show_time',
            field=models.ForeignKey(default=100.0, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seats.showtime'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
